### ISSUE TITLE
ITS Portal cannot deploy tokens - It’s stuck on “Check Your Wallet"

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelarjs#274] opened 2024-03-12 10:51 UTC
On Mainnet:

![image](https://github.com/axelarnetwork/axelarjs/assets/45847909/6fe53b0a-843d-4676-83a8-587c249cd905)

**Comment by canhtrinh** [comment] 2024-03-12 17:19
root cause is in underlying contracts. being addressed now

**Comment by canhtrinh** [comment] 2024-03-12 17:50
this issue was fixed downstream. closing ticket

**Closed by canhtrinh** 2024-03-12 17:50 UTC
Labels: bug, interchain-portal
