### ISSUE TITLE
Register Button Keeps Loading Without Confirmation Popup After Chain Selection

### ISSUE THREAD

**Issue by Olanetsoft** [axelarnetwork/axelarjs#288] opened 2024-03-18 11:47 UTC
It works fine on the testnet but fails on the mainnet.  Here is the token address on eth mainnet. 0xe97F6dDE78b11B58cB3e394F15ab592Cb2ACd290

**Comment by canhtrinh** [comment] 2024-03-19 17:22
the root cause of this is a known UI issue, i'll try to patch a fix this week. can you tell me:
* what wallet the user used?
* what browser?

**Comment by Olanetsoft** [comment] 2024-03-19 17:53
I am confirming this and will give you feedback soon.

**Comment by Olanetsoft** [comment] 2024-03-20 11:32
Tried on Chrome and Firefox. The wallet is MetaMask

**Comment by canhtrinh** [comment] 2024-03-20 18:57
still addressing the actual root cause of the issue, but there is a "fix" (more like a technical simplification) we have live in testnet now. can you ask if they can try going through the same steps on testnet and seeing that works for them?

**Comment by canhtrinh** [comment] 2024-03-24 18:10
@Olanetsoft confirmed that the fix deployed in this version (https://github.com/axelarnetwork/axelarjs/blob/env/mainnet/apps/maestro/CHANGELOG.md#036) addressed their issue, and that the partner tried deploying in testnet successfully. this was just promoted to mainnet, so closing this ticket

**Closed by canhtrinh** 2024-03-24 18:10 UTC
Labels: bug, interchain-portal
